
version: '3.9'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    env_file:
      - ../apps/backend/.env
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
