name: FleeHy CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm --prefix apps/backend run prisma:generate

      - name: Build frontend
        run: npm --prefix apps/frontend run build

      - name: Verify success
        run: echo "✅ Build completed successfully!"
